<?php $this->assets->outputCss(); ?> 
<nav class="navbar   sticky-top">
    <img class="img-fluid " alt="Responsive image" height='80' width='80' src="<?php echo $this->url->get('img/jn.png')?>">
    <div class="nav navbar-nav-scroll" >
        <button class="btn c" onclick="window.location = '/JobsNow/login'">Login</button>
        <button class="btn" onclick="window.location = '/JobsNow/register'">Register</button>
    </div>
</nav>

<div class="text-center">
    <img class="animacion" height='50%' width='50%' src="<?php echo $this->url->get('img/logo.png')?>">
</div>
<div class='container description'>
    Nuestro fin?  Acabar con el desempleo de la era macri. Con esta herramienta desarrollada 100% por argentinos, podras encontrar empleo en cuestion de horas, deja de preocuparte y registrate ya para conseguir un buen empleo.
</div>

<div class="experience">
    <div class='user'>
        <div class="row">
            <div class="text-center col-sm-12 col-md-3">
                <img width="150" height="150" class="torip rounded-circle" src="<?php echo $this->url->get('img/tori.jpg')?>"><br>
                <q>Muy Buena la Página</q>
            </div>
            <div class="text-center col-sm-12 col-md-3">
                <img width="150" height="150" class="nhdbp rounded-circle" src="<?php echo $this->url->get('img/nhdb_profile.jpg')?>"><br>
                <q>Muy Buena la Página</q>
            </div>
            <div class="col-sm-12 col-md-6">
                <p class="usersp">
                    Las experiencias de nuestros usuarios son excelentes e indican que en un periodo de 24 horas pueden encontrar trabajo.
                </p>
            </div>
        </div>
    </div>
</div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
            <a href='https://scontent-eze1-1.cdninstagram.com/vp/c3979dcd87fca69b7f7bdf45fc6e18bc/5DC4C67C/t51.2885-15/e35/30855377_958145524351383_4567069795077324800_n.jpg?_nc_ht=scontent-eze1-1.cdninstagram.com' target='_blank'><img class="footerimg jobsnow" src="<?php echo $this->url->get('img/textlogo.png')?>"></a>
            </div>
            <div class="col-sm-3">
                <h2>Nuestros datos:</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <a href="https://www.unlam.edu.ar/" target='_blank'><img class="footerimg unlam" src="<?php echo $this->url->get('img/logo-unlam.png')?>"></a>
            </div>
            <div class="end col-sm-3 ">    
                <div class="tori">
                    <a href="https://scontent-eze1-1.cdninstagram.com/vp/1a5b63c72c3db2fd1d88b1ee8fc355db/5DBC6AE2/t51.2885-15/e35/36603179_2073343849574826_7044634126590148608_n.jpg?_nc_ht=scontent-eze1-1.cdninstagram.com" target='_blank'><h5>Toripampa</h5></a>
                    <ul>
                        <li><a href="https://www.instagram.com/toripampa/" target='_blank'>Instagram</a></li>
                        <li><a href="https://twitter.com/toripampa" target='_blank'>Twitter</a></li>
                        <li><a href="https://toripampa.bandcamp.com/" target='_blank'>Bandcamp</a></li>
                    </ul>
                </div>
            </div>
            <div class="end col-sm-3">
                <div class="nhdb">
                    <a href="https://scontent-eze1-1.cdninstagram.com/vp/3624044ecc4eba31fec693b6914b383f/5DACD80C/t51.2885-15/e35/18381986_256649364742703_8595268408805687296_n.jpg?_nc_ht=scontent-eze1-1.cdninstagram.com" target='_blank'><h5>Nhdb</h5></a>
                    <ul>
                        <li><a href="https://www.instagram.com/nahuel__de__bellis/" target='_blank'>Instagram</a></li>
                        <li><a href="https://twitter.com/_NHDB" target='_blank'>Twitter</a></li>
                        <li><a href="https://github.com/nahueldebellis" target='_blank'>GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
                Proyecto de pasantias desarrollado en Phalcon, HTML, CSS y JavaScript.
                Agradecimientos: Emanuel Carbone, Horacio Villarreal, Daniela Turello, Luca Salman y Barack Obama.
        </div>
    </div>
</footer>