<?php
    function showOffers($offer, $apply='', $url="/JobsNow/postulation/apply/"){
        if(isset($offer)){
            foreach($offer as $off){ ?>
                <br>
                <form action=<?php echo $url ?> method='POST'>
                    <?php
                        foreach($off as $campo => $value){
                            if($campo == 'requirements' || $campo == 'description')
                                echo "<br><textarea> $value </textarea> <br><br>";
                            else if($campo != "id")
                                echo "<input name=$campo value='$value' readonly> <br>";
                            else
                                echo "<input type='hidden' name=$campo value='$value' readonly> <br>";
                        }
                        echo $apply;
                        echo "<br><br>";
                    ?>
                </form>
                <?php
            }
        }
    }

    if(isset($create)){
        ?>
        <h2>Create new Offer</h2>
        <form action="<?php echo $create; ?>" method="post">
            <input type="hidden" name="id" value="<?php echo $company_id ?>">
            <input type="text" name="position" id="" placeholder="Position">
            <input type="text" name="description" id="" placeholder="Description">
            <input type="text" name="salary" id="" placeholder="Salary">
            <input type="text" name="requirements" id="" placeholder="Requirements">
            <input type="submit" value="Create">
        </form>
        <?php
        $apply = "<input type='submit' value='See postulants'>";
        $url="/JobsNow/postulation/show/";
        showOffers($offer, $apply, $url);
    }
    else{
        $apply = "<input type='submit' value='Apply'>";
        showOffers($offer, $apply);
    }
    
?> 