<form action="/JobsNow/register/register" method ="post"><br>
    <input type="text" name = "name" placeholder = "name"><br>
    <input type="password" name = "pass" placeholder = "password"><br>
    <input type="email" name="email" placeholder = "email"><br>
    <input type="text" name="phone" placeholder = "phone"><br>
    <input type="text" name="address" placeholder = "address"><br>
    <input type="text" name="rotulo" placeholder = "rotulongo"><br>
    <input type="file" name="profile_photo" placeholder = "profile picture"><br>
    <select name='type'>
        <option value='Employee'> Employee</option>
        <option value='Company'> Company</option>
    </select>
    <div id="root"><div>
</form>
