<form action="/JobsNow/register/register" method ="post" id='user_form' enctype="multipart/form-data" >
    <input type="text" name = "name" placeholder = "name"><br>
    <input type="password" name = "pass" placeholder = "password"><br>
    <input type="email" name="email" placeholder = "email"><br>
    <input type="text" name="phone" placeholder = "phone"><br>
    <input type="text" name="address" placeholder = "address"><br>
    <input type="text" name="rotulo" placeholder = "rotulo"><br>
    <label for="">Profile photo: </label>
    <input type="file" name="profile_photo"><br>
    <select name='type' id='type'>
        <option value="Seleccione chorongo">Select user type</option>
        <option value='Employee'> Employee</option>
        <option value='Company'> Company</option>
    </select><br>
    <div id="extra"></div>
</form>
<?php echo $this->assets->outputJs(); ?>