<?php $this->assets->outputCss(); ?>

<nav class="navbar navbar-expand-lg navbar sticky-top">
    <img class="img-fluid " alt="Responsive image" height='80' width='80' src="<?php echo $this->url->get('img/jn.png')?>" onclick="window.location = '/JobsNow/'">
</nav>

<div class="container">
    <h1>Registrate</h1>
    <form class="form-group" action="/JobsNow/register/register" method ="post" id='user_form' enctype="multipart/form-data" >
        <div class="form-group">
            <input class="form-control" type="text" name = "name" placeholder = "Name">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name = "pass" placeholder = "Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder = "Email">
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="phone" placeholder = "Phone">
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="address" placeholder = "Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="rotulo" placeholder = "Rotulo">
        </div>
        <div class="form-group">
            <label for="">Profile photo: </label>
            <input class="form-control-file" type="file" name="profile_photo">
        </div>
        <div class="input-group mb-3">
            <select class="custom-select" name='type' id='type'>
                <option value="Seleccione chorongo">Select user type</option>
                <option value='Employee'> Employee</option>
                <option value='Company'> Company</option>
            </select>
        </div>
        <div id="extra"></div>
    </form>
</div>
<?php echo $this->assets->outputJs(); ?>