<h1> <?php echo $info['name']; ?> </h1>
<img class="img-responsive center-block" 
     src="data:image/jpeg;base64,<?php echo $info['profile_photo']?>">
<p>
     <?php
          foreach ($info as $campo => $value) {
               if(($campo != "profile_photo") && ($campo != "cv")){
                    echo "$campo -> $value<br>";
               }
          } 
     ?>

     <iframe id="pdf" src="" type="application/pdf" width="100%" height="100%" style="overflow: auto;">
    </iframe>
     <a href='/jobsnow/profile/close/'>Close Session</a>

</p>