<?php 
    echo $this->assets->outputCss();
    $this->assets->outputJs();
?>

<form class="form-group" action='/JobsNow/profile/edit' method='POST'>
  
    <?php
        foreach($user_info as $change_field => $old_data){
            if($change_field != "type"){
                echo "<label>$change_field</label>";
                echo "<input class='form-control' type='text' name='$change_field' placeholder='$old_data'>";
            }
        }
    ?>

    <div class="form-group">
        <label>Password: </label>
        <input class="form-control" type="password" name="pass" placeholder = "Password">
    </div>

    <div class="form-group">
        <label>Profile Photo: </label>
        <input class="form-control-file" type="file" name="profile_photo" placeholder = "Name">
    </div>
    <?php 
        foreach($aditional_info as $input_name => $input_type){
            echo "<label>$input_name: </label><br/>";
            $input_class =  $input_type == "file" ? "-file" : '';
            echo "<input class='form-control$input_class' type='$input_type' name='$input_name' placeholder=$input_name><br>";
        }
    ?>
    <input class="btn btn-primary update" type="submit" value="Update">
</form>