<?php $this->assets->outputCss(); ?>
<header class="navbar navbar-dark flex-row bd-navbar sticky-top">
        <img class="img-fluid " alt="Responsive image" height='80' width='80' src="<?php echo $this->url->get('img/jn.png')?>" onclick="window.location = '/JobsNow/profile/'">
        <ul class="nav navbar-nav-scroll ">
            <li class='nav_item '>
                <iframe class='' style="border: 0; width: 100%; height: 42px;" src="https://bandcamp.com/EmbeddedPlayer/track=4189259381/size=small/bgcol=333333/linkcol=0f91ff/transparent=true/" seamless><a href="http://toripampa.bandcamp.com/track/breathe">Breathe by Toripampa</a></iframe>
            </li>
            <li class="nav-item active">
                <button class="btn" onclick="window.location='/jobsnow/Profile/Close'">Close Session</a> 
            </li>
            <li class="nav-item active">
                <button class="btn c" onclick="window.location='/jobsnow/Postulation/'">Ofertas</a> 
            </li>   
        </ul>

</header>

<div class='container'>
    <?php echo $this->getContent(); ?>
</div>