<?php 
    $this->assets->outputCss(); 
    $this->assets->outputJs();
?>
<header class="navbar navbar-dark flex-row bd-navbar sticky-top">
    <img class="img-fluid" alt="Responsive image" height='80' width='80' src="<?php echo $this->url->get('img/jn.png')?>" onclick="window.location = '/JobsNow/profile/'">
    <ul class="nav navbar-nav-scroll ">
        <li class='nav_item'>
            <div class="md-form active-purple active-purple-2">
                <form action='/jobsnow/search/results' method='POST'>
                    <div class='dropdown'>
                        <input id="search" class="form-control" name="search" type="text" placeholder="Buscar" autocomplete="off">
                        <div id='menu' class="dropdown-menu">
                            <div id="partial_result">
                            </div>
                        </div> 
                    </div>
                </form>
            </div>
        </li>
        <li class="nav-item active">
            <button class="btn" onclick="window.location='/jobsnow/Profile/Close'">Close Session</a> 
        </li>
        <li class="nav-item active">
            <button class="btn c" onclick="window.location='/jobsnow/Postulation/'">Ofertas</a> 
        </li>   
    </ul>
</header>

<div class='container'>
    <?php echo $this->getContent(); ?>
</div>